# Properties of Dot Product - Lab

## Introduction

In this lab, you'll be practicing some interesting properties of a Dot Product-type matrix multiplication. Understanding these properties will become useful as you move forward with machine learning. The lab will require you to calculate results to provide a proof for these properties.

## Objectives
You will be able to:
* Understand and analytically explain Distributive, Commutative and Associative properties of dot product

## Instructions

* For each property, create suitably sized matrices with random data and prove the equations 
* Ensure that size/dimension assumptions are met while performing calculations (you'll see errors otherwise)
* Calculate the LHS and RHS for all equations and show if they are equal or not

## Distributive Property - matrix multiplication is distributive

### Prove that $A \cdot (B+C) = (A \cdot B + A \cdot C) $

In [22]:
import numpy as np

def create_random_matrix(n,m):
    Z = np.zeros((n,m))
    
    for i in range(n):
        for j in range(m):
            Z[i,j] = np.random.randint(1,10)
    
    return Z

def add_matrices(X, Y):
    if X.shape != Y.shape:
        raise ValueError('Error can\'t add two matrices with different shapes')
    
    return X + Y

def dot_matrices(X, Y):
    if X.shape[1] != Y.shape[0]:
        raise ValueError('Error can\'t dot multiply two matrices not matching X cols = Y rows')
    
    return X.dot(Y)

A = create_random_matrix(4,4)
B = create_random_matrix(4,4)
C = create_random_matrix(4,4)

print(dot_matrices(A,add_matrices(B,C)))
print(add_matrices(dot_matrices(A,B),dot_matrices(A,C)))

print(dot_matrices(A,add_matrices(B,C)) == add_matrices(dot_matrices(A,B),dot_matrices(A,C)))

[[267. 305. 310. 242.]
 [203. 282. 271. 177.]
 [119. 140. 147. 101.]
 [208. 246. 208. 177.]]
[[267. 305. 310. 242.]
 [203. 282. 271. 177.]
 [119. 140. 147. 101.]
 [208. 246. 208. 177.]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


## Associative Property - matrix multiplication is associative
### Prove that $A \cdot (B \cdot C) = (A \cdot B) \cdot C $

In [24]:
# Your code here 
A = create_random_matrix(4,4)
B = create_random_matrix(4,4)
C = create_random_matrix(4,4)

print(dot_matrices(A,dot_matrices(B,C)))
print(dot_matrices(dot_matrices(A,B), C))

[[2106. 3546. 1696. 3310.]
 [2191. 3671. 1668. 3311.]
 [2312. 3862. 1813. 3653.]
 [2087. 3707. 1702. 3265.]]
[[2106. 3546. 1696. 3310.]
 [2191. 3671. 1668. 3311.]
 [2312. 3862. 1813. 3653.]
 [2087. 3707. 1702. 3265.]]


## Commutative Property - matrix multiplication is NOT commutative
### Prove that for matrices, $A \cdot B \neq B \cdot A $

In [26]:
# Your code here 
A = create_random_matrix(3,4)
B = create_random_matrix(4,3)

print(dot_matrices(A,B))
print(dot_matrices(B,A))

[[114.  22.  77.]
 [160.  37. 104.]
 [ 90.  17.  62.]]
[[  7.  43.  32.  30.]
 [ 18. 100.  80.  50.]
 [ 10.  59.  47.  33.]
 [ 16.  95.  73.  59.]]


## Commutative Property -  vector multiplication IS commutative
### Prove that for vectors,  $x^T \cdot y = y^T \cdot x$
Note: superscipt<sup>T</sup> denotes the transpose we saw earlier

In [29]:
# Your code here 
# Your code here 
A = create_random_matrix(3,1)
B = create_random_matrix(3,1)

print(A)
print(B)
print(dot_matrices(A.T,B))
print(dot_matrices(B.T,A))

[[2.]
 [5.]
 [4.]]
[[1.]
 [5.]
 [9.]]
[[63.]]
[[63.]]


## Simplification of the matrix product
### Prove that $ (A \cdot B)^T = A^T \cdot B^T $

In [38]:
A = create_random_matrix(4,4)
B = create_random_matrix(4,4)

# A = np.array([[2, 3], [1, 4], [7, 6]])
# B = np.array([[5, 3], [2, 2]])

print(A)
print(B)
C = dot_matrices(A,B)
print(C)
print(C.T)

left = np.transpose(A.dot(B))
right = np.transpose(B).dot(np.transpose(A))
print(left == right)

print(dot_matrices(A,B).T)
print(dot_matrices(A.T,B.T))

[[4. 8. 5. 4.]
 [1. 7. 6. 5.]
 [7. 4. 2. 3.]
 [7. 3. 5. 1.]]
[[9. 4. 9. 7.]
 [6. 4. 2. 5.]
 [9. 4. 9. 5.]
 [2. 4. 2. 1.]]
[[137.  84. 105.  97.]
 [115.  76.  87.  77.]
 [111.  64.  95.  82.]
 [128.  64. 116.  90.]]
[[137. 115. 111. 128.]
 [ 84.  76.  64.  64.]
 [105.  87.  95. 116.]
 [ 97.  77.  82.  90.]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
[[137. 115. 111. 128.]
 [ 84.  76.  64.  64.]
 [105.  87.  95. 116.]
 [ 97.  77.  82.  90.]]
[[152.  77. 138.  33.]
 [157.  99. 151.  55.]
 [122.  83. 112.  43.]
 [ 90.  55.  88.  35.]]


## Summary 

You've seen enough matrix algebra by now to solve a problem of linear equations as you saw earlier. You'll now see how to do this next. 